name: Tests
on: # Run on all pushes and pull requests
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      EIA_API_KEY: ${{ vars.EIA_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Print environment variables
        run: |
          echo "EIA_API_KEY: $EIA_API_KEY"
        env:
          EIA_API_KEY: ${{ vars.EIA_API_KEY }}
      - name: Install dependencies
        run: |
          python -m pip install ".[test]"
      - name: Run unit tests without coverage
        if: ${{ matrix.python-version != '3.11' }}
        run: |
          make test

      - name: Run unit tests with coverage
        if: ${{ matrix.python-version == '3.11' }}
        run: |
          make test-cov
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/coverage.xml
          fail_ci_if_error: true
          verbose: true
